### ISSUE TITLE
Mention that contain emojis cause the text view to get stuck using the mention attributes for regular text

### ISSUE THREAD

**Issue by raphaelcruzeiro** [szweier/SZMentionsSwift#38]
<img width="320" alt="screen shot 2017-02-07 at 14 45 14" src="https://cloud.githubusercontent.com/assets/425640/22695908/4900abf0-ed44-11e6-8756-91112a2463b4.png">

Not exactly sure what the problem is yet.  I guess `SZMentionHelper` is the first place I should start looking?

**Comment by szweier** [comment]
Yea that's probably the best place to start, likely `forceDefaultAttributes` function.

**Comment by szweier** [comment]
@raphaelcruzeiro are you able to replicate this issue using the example app?

**Comment by szweier** [comment]
I'm unable to replicate this issue, can you provide more info on the setup.

**Comment by raphaelcruzeiro** [comment]
Interesting. I am unable to replicate this with the example app. Which means that I am probably setting this up wrong.

This is how I am setting up the mentions on my `init` method:

```
mentionsManager.delegate = self

        mentionsListener = SZMentionsListener(mentionTextView: textView, mentionsManager: self, mentionTextAttributes: mentionAttributes(), defaultTextAttributes: defaultAttributes())
        mentionsDataSource = MentionDataSource(listener: mentionsListener)
        mentionsDataSource.registerCells(tableView: mentionsTableView)
        mentionsTableView.dataSource = mentionsDataSource
        mentionsTableView.delegate = mentionsDataSource
        mentionsTableView.separatorStyle = .none

        textView.attributedText = text != nil ? NSAttributedString(string: text!) : nil

        if mentions.count > 0 {
            mentionsListener.insertExistingMentions(mentions)
        }
```

I don't see anything obviously wrong with this. Any ideas?

**Comment by szweier** [comment]
The only thing I'm noticing in that example is that you're setting the attributedText on the UITextView.  If you look at the `SZExampleAccessoryView.swift` file there's an example of using this library with inserting mentions.  On line 26 you'll see I'm setting up the TextView's text rather than attributed text.  The library should handle changing colors etc.  Maybe that's the problem.

**Comment by szweier** [comment]
I've also merged in a change for an issue with editing mentions into master (not yet released) if you want to try that out to see if it helps as well.

**Comment by raphaelcruzeiro** [comment]
Still having the same issues. I figured it might have something to do with an extension that I use for setting a placeholder on the text view but after disabling that the problem persisted.

I debugged both apps (mine and the example) and it seems that all the methods are being called correctly, though this is what happens on my app:

 Some text here **Someuser 🐍🐞** t**his text shouldn't be bold**

Notice that the first letter after the mention uses the default attributes and the ones after that use the mentions attributes.

**Comment by szweier** [comment]
Very strange, can you create a public repo with an example that I can pull down and try to work out the bug on?

**Comment by raphaelcruzeiro** [comment]
I managed to replicate the issue with this sample project:

https://github.com/raphaelcruzeiro/MentionsOnTextView

**Comment by szweier** [comment]
I've only gotten to dig a little bit so far but, the one very interesting thing I've noticed is that it's actually only changing the font back to the mention attribute and it's not changing the color back to mention attribute.  Something very strange is going on because of that emoji.  Thought this info might give you an idea if I can't find it.

**Comment by szweier** [comment]
So this is interesting, the Emoji used throws the logic for attributed strings for a loop.  http://stackoverflow.com/questions/22826943/nsattributedstring-reporting-incorrect-sizes-for-uitextview-sizethatfits-and-bou NSOriginal font gets added and it seems as though the string is using original font to continue on as typing continues.  I'm not sure I've found a fix just yet but that's the latest.

**Comment by szweier** [comment]
@raphaelcruzeiro I believe I've solved it.  Please try https://github.com/szweier/SZMentionsSwift/pull/40 and let me know if this works.  It seems to have worked in your example (thank you for that)

**Comment by raphaelcruzeiro** [comment]
@szweier Works like a charm!

**Comment by szweier** [comment]
Glad to hear.
